version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-PHP
    ports:
      - 8080:80
    volumes:
      - ./html:/app
    depends_on: 
      - mongo
  mongo:
    image: mongo:latest